services:
  llonebot-docker:
    image: mlikiowa/llonebot-docker
    tty: true
    container_name: llonebot-docker
    restart: always
    ports:
      - "6099:6099"
      - "3000:3000"    
      - "3001:3001"
    # - "3001:3001" 留给反向
    environment:
      - TZ=Asia/Shanghai
      - VNC_PASSWD=vncpasswd
    volumes:
      - ./LiteLoader/:/opt/QQ/LiteLoader/
      # 未固化QQ数据 当前仅固化LiteLoader
